#!/usr/bin/env zsh

[[ $OSTYPE =~ darwin ]] || exit 34

# Actual Source Files/Folders
source_files=($XDG_CONFIG_HOME/idea/colors)

for idea_pref_folder in ~/Library/Preferences/{IntelliJ,PhpStorm,RubyMine,PyCharm,DataGrip}*(N); do
    ink -l -c green "[idea] Symlinking $idea_pref_folder"
    symlink-files "$source_files" "$idea_pref_folder"
    clean-symlinks "$idea_pref_folder"
done
