#!/usr/bin/env zsh

(( $+commands[pip] )) || return 34

pip install -U \
    pip setuptools \
    virtualenv \
    pygments \
    tmuxp \
    doge \
    http-prompt

pip3 install -U \
    pip \
    git-repo

pygmentspath=$(python -c "import pygments, inspect, os; print(os.path.dirname(os.path.abspath(inspect.getsourcefile(pygments))))")/styles
if [[ ! -f "$pygmentspath/base16_oceanicnext_dark.py" ]]; then
  ink -l -c magenta -- "-- Adding Pygments Color"
  cp $DOTFILES/plugins/python/etc/base16_oceanicnext_dark.py $pygmentspath/
fi
