#!/usr/bin/env bash

is_ssh_running && return

if is_screen_or_tmux_running; then
    if is_tmux_runnning; then
        echo ' _____ __  __ _   ___  __ '
        echo '|_   _|  \/  | | | \ \/ / '
        echo '  | | | |\/| | | | |\  /  '
        echo '  | | | |  | | |_| |/  \  '
        echo '  |_| |_|  |_|\___//_/\_\ '
        export DISPLAY="$TMUX"
    elif is_screen_running; then
        # For GNU screen
        :
    fi
else
    tmux new -As base
fi
