#!/usr/bin/env zsh

[[ ! -z "$SSH_CONNECTION" ]] && return

if [ ! -z "$TMUX" ]; then
    echo ' _____ __  __ _   ___  __ '
    echo '|_   _|  \/  | | | \ \/ / '
    echo '  | | | |\/| | | | |\  /  '
    echo '  | | | |  | | |_| |/  \  '
    echo '  |_| |_|  |_|\___//_/\_\ '
    export DISPLAY="$TMUX"
elif [ ! -z "$STY" ]; then
    # For GNU screen
    :
else
    tmux new -As base
fi
