#!/usr/bin/env zsh


[[ "$1" != "dump" ]] && command brew $@

# Shift one argument if it's cask
[[ "$1" == "cask" ]] && shift

homebrew-dump() {
    command brew file init --on_request -F bundle -y
}

case "$1" {
    instal|install|reinstall|tap|pip|gem|rm|remove|uninstall|untap)
        homebrew-dump >/dev/null 2>&1 &!
        ;;
    dump)
        homebrew-dump
        ;;
}
