#!/usr/bin/env zsh

# @TODO: This needs work. =/

local aliasname="$1"
local filename="/tmp/drush-env-${USER}/drush-drupal-site-$$"

mkdir -p ${filename:h}

if [[ -z $aliasname ]]; then
    rm -f $filename
else
    echo $aliasname > $filename
fi
