#!/usr/bin/env zsh

# print opened connections, filtered by known applications.

# 2BUA8C4S2 = 1password
local ignore=(Google Dropbox Slack Mail 2BUA8C4S2)
sudo lsof -nPi TCP | grep -v "^${(j:\|:)ignore}"
