#!/usr/bin/env zsh

function print_error() {
    ink -l -c red "$@"
}

function print_status() {
    ink -l -c blue "$@"
}

local apps_directory=$DOTFILES/plugins/apps

# Set OS X defaults
#is_osx && print_status "Installing OSX Defaults..." && $apps_directory/osx.sh &!

# Install homebrew packages
is_osx && print_status "Installing Homebrew Packages..." && $apps_directory/homebrew.sh

# Linix Packages, right now only ubuntu..
is_linux && print_status "Installing Ubuntu Packages..." && $apps_directory/ubuntu.sh

# Install python packages
{ (( $+commands[pip] )) && print_status "Installing Python Packages..." && $apps_directory/python.sh} || print_error "Python is not installed or failed. Skipping..."

# Install node packages
{ (( $+commands[node] )) && print_status "Installing Node Packages..." && $apps_directory/node.sh} || print_error "Node is not installed or failed. Skipping..."

# Install ruby packages
{ (( $+commands[ruby] )) && print_status "Installing Ruby Packages..." && $apps_directory/ruby.sh} || print_error "Ruby is not installed or failed. Skipping..."

# Install vim packages
{ (( $+commands[vim] )) && print_status "Installing VIM Packages..." && $apps_directory/vim.sh} || print_error "Vim is not installed or failed. Skipping..."
