#!/usr/bin/env zsh

function print_status() {
    ink -l -c blue "$@"
}

function include_dot() {
  local dots_directory=$DOTFILES/plugins/apps/dots
  subdotfile="$1"
  ink -l -c blue "$2"
  source $dots_directory/$subdotfile.zsh
  (( $+commands[hr] )) && hr ' ' '-=' ' '
}

if [[ -n "$1" ]]; then
  # Just run the one dot we passed in
  include_dot $1 "Running $1 dot"
  return  
fi

# Set OS X defaults
# is_macos && include_dot osx "Running MacOS Defaults dot..."

# Install homebrew packages
is_macos && include_dot homebrew "Running Homebrew dot"

# Linix Packages, right now only ubuntu..
is_linux && include_dot ubuntu "Running Ubuntu dot"

# Install python packages
include_dot python "Running Python dot"

# Install node packages
include_dot node "Running Node dot"

# Install ruby packages
include_dot ruby "Running Ruby dot"

# Install vim packages
include_dot vim "Running VIM dot"

# Vagrant plugins:
# vagrant-auto_network
# vagrant-cachier
# vagrant-hostsupdater
# vagrant-share
