#!/usr/bin/env zsh

function print_error() {
    ink -l -c red "$@"
}

function print_status() {
    ink -l -c blue "$@"
}

local apps_directory=$DOTFILES/plugins/apps

# Set OS X defaults
#is_osx && print_status "Installing OSX Defaults..." && $apps_directory/osx.zsh

# Install homebrew packages
is_macos && print_status "Installing Homebrew Packages..." && $apps_directory/homebrew.zsh

# Linix Packages, right now only ubuntu..
is_linux && print_status "Installing Ubuntu Packages..." && $apps_directory/ubuntu.zsh

# Install python packages
{ (( $+commands[pip] )) && print_status "Installing Python Packages..." && $apps_directory/python.zsh} || print_error "Python is not installed or failed. Skipping..."

# Install node packages
{ (( $+commands[node] )) && print_status "Installing Node Packages..." && $apps_directory/node.zsh} || print_error "Node is not installed or failed. Skipping..."

# Install ruby packages
{ (( $+commands[ruby] )) && print_status "Installing Ruby Packages..." && $apps_directory/ruby.zsh} || print_error "Ruby is not installed or failed. Skipping..."

# Install vim packages
{ (( $+commands[vim] )) && print_status "Installing VIM Packages..." && $apps_directory/vim.zsh} || print_error "Vim is not installed or failed. Skipping..."

print_status "Installing xterm-256color-italic terminfo" && tlc $DOTFILES/plugins/apps/term/xterm-256color-italic.terminfo

# Vagrant plugins:
# vagrant-auto_network
# vagrant-cachier
# vagrant-hostsupdater
# vagrant-share
