#!/usr/bin/env zsh

(( $+commands[node] )) || exit 34


ink -l -c green -- "[node] Setting node config"
mkdir -p $XDG_DATA_HOME/node
npm config set cache $XDG_CACHE_HOME/npm
npm config set devdir $XDG_DATA_HOME/node/gyp

ink -l -c green -- "[node] Installing npm Packages"
npm install -g \
    npm \
    bcat \
    gulp \
    bower \
    yo \
    coffee-script \
    fkill-cli \
    tldr \
    speed-test \
    spoof \
    ctrace \
    babel-cli
