#!/usr/bin/env zsh

(( $+commands[node] )) || exit 34

ink -l -c green -- "[node] Installing npm Packages"
npm install -g \
    npm \
    gulp \
    bower \
    yo \
    coffee-script \
    fkill-cli \
    tldr \
    speed-test \
    spoof \
    ctrace \
    babel-cli
