
# tap repositories and their packages

tap 'caskroom/cask'
cask '1password'
cask 'aerial'
cask 'alcatraz'
cask 'alfred'
cask 'android-studio'
cask 'anybar'
cask 'archiver'
cask 'atom'
cask 'bettertouchtool'
cask 'betterzipql'
cask 'bitbar'
cask 'captain'
cask 'charles'
cask 'dash'
cask 'default-folder-x'
cask 'discord'
cask 'docker'
cask 'dropbox'
cask 'electrum'
cask 'exa'
cask 'firefox'
cask 'gear-player'
cask 'gitup'
cask 'google-chrome'
cask 'hopper-disassembler'
cask 'hosts'
cask 'iina'
cask 'imageoptim'
cask 'interarchy'
cask 'jadengeller-helium'
cask 'java'
cask 'jetbrains-toolbox'
cask 'karabiner'
cask 'kitematic'
cask 'launchrocket'
cask 'meld'
cask 'mono-mdk'
cask 'nzbvortex'
cask 'osxfuse'
cask 'paw'
cask 'provisionql'
cask 'psequel'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'qlvideo'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'rcdefaultapp'
cask 'renamer'
cask 'sequel-pro'
cask 'slack'
cask 'sourcetree'
cask 'sqlpro-studio'
cask 'steam'
cask 'suspicious-package'
cask 'synergy'
cask 'textual'
cask 'torbrowser'
cask 'totalfinder'
cask 'tower'
cask 'tunnelbear'
cask 'vagrant-manager'
cask 'vagrant'
cask 'vimr'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'webpquicklook'
cask 'wireshark'
cask 'wmail'
cask 'xquartz'

tap 'caskroom/fonts'
cask 'font-fira-code'
cask 'font-roboto'
cask 'font-source-code-pro'

tap 'caskroom/versions'
cask 'firefoxdeveloperedition'
cask 'google-chrome-canary'
cask 'iterm2-nightly'

tap 'homebrew/boneyard'
brew 'lftp'

tap 'homebrew/bundle'

tap 'homebrew/command-not-found'

tap 'homebrew/completions'

tap 'homebrew/core'
brew 'android-platform-tools'
brew 'ansible'
brew 'asciidoc'
brew 'asciiquarium'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'bash-completion'
brew 'bdw-gc'
brew 'bfg'
brew 'binutils'
brew 'boost'
brew 'boxes'
brew 'brew-cask-completion'
brew 'cairo'
brew 'cloc'
brew 'cmake'
brew 'cmatrix'
brew 'cocoapods'
brew 'coreutils'
brew 'cowsay'
brew 'cscope'
brew 'ctags'
brew 'curl'
brew 'dateutils'
brew 'desk'
brew 'diff-so-fancy'
brew 'docbook'
brew 'docbook-xsl'
brew 'docker-completion'
brew 'docker-compose-completion'
brew 'docker-machine-completion'
brew 'dockviz'
brew 'dos2unix'
brew 'doxygen'
brew 'fasd'
brew 'ffmpeg'
brew 'figlet'
brew 'findutils', args: ['with-default-names']
brew 'fontconfig'
brew 'fortune'
brew 'freetype'
brew 'fswatch'
brew 'fzf'
brew 'gawk'
brew 'gcc'
brew 'gdb'
brew 'gdbm'
brew 'gettext'
brew 'ghq'
brew 'git'
brew 'git-extras'
brew 'git-fixup'
brew 'git-ftp'
brew 'glew'
brew 'glib'
brew 'gmp'
brew 'gnu-sed', args: ['with-default-names']
brew 'gnu-tar', args: ['with-default-names']
brew 'gnu-which', args: ['with-default-names']
brew 'go'
brew 'gobject-introspection'
brew 'gource'
brew 'gradle'
brew 'grc'
brew 'gron'
brew 'gti'
brew 'heroku'
brew 'highlight'
brew 'hr'
brew 'html-xml-utils'
brew 'htop-osx'
brew 'httpie'
brew 'httpstat'
brew 'hub'
brew 'icu4c'
brew 'iftop'
brew 'imagemagick', args: ['with-webp']
brew 'iozone'
brew 'ipcalc'
brew 'isl'
brew 'jemalloc'
brew 'jpeg'
brew 'jq'
brew 'lame'
brew 'lastpass-cli', args: ['with-pinentry']
brew 'libassuan'
brew 'libevent'
brew 'libewf'
brew 'libffi'
brew 'libgpg-error'
brew 'libmagic'
brew 'libmpc'
brew 'libpng'
brew 'libsass'
brew 'libssh2'
brew 'libtermkey'
brew 'libtiff'
brew 'libtool'
brew 'libuv'
brew 'libvterm'
brew 'libxml2'
brew 'libyaml'
brew 'livestreamer'
brew 'lua'
brew 'lua@5.1'
brew 'mackup'
brew 'macvim', args: ['with-override-system-vim']
brew 'mariadb'
brew 'mas'
brew 'miller'
brew 'moreutils', args: ['without-parallel']
brew 'mpfr'
brew 'msgpack'
brew 'mtr'
brew 'multitail'
brew 'mycli'
brew 'netcat'
brew 'ngrep'
brew 'nmap'
brew 'no-more-secrets'
brew 'node'
brew 'noti'
brew 'oniguruma'
brew 'openssl'
brew 'openssl@1.1'
brew 'p7zip'
brew 'parallel'
brew 'pcre'
brew 'phantomjs'
brew 'pidcat'
brew 'pigz'
brew 'pinentry'
brew 'pixman'
brew 'pkg-config'
brew 'pngcheck'
brew 'postgresql'
brew 'protobuf'
brew 'pup'
brew 'pv'
brew 'python'
brew 'python3'
brew 'radare2'
brew 'ranger'
brew 'readline'
brew 'reattach-to-user-namespace', args: ['with-wrap-launchctl']
brew 'redis'
brew 'renameutils'
brew 'ruby'
brew 'sassc'
brew 'screenresolution'
brew 'sdl2'
brew 'sdl2_image'
brew 'slackcat'
brew 'slurm'
brew 'socat'
brew 'spark'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'stormssh'
brew 'stow'
brew 'surfraw'
brew 'swig'
brew 'syncthing'
brew 'syncthing-inotify'
brew 'textql'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'unibilium'
brew 'unison'
brew 'unixodbc'
brew 'unrar'
brew 'v8'
brew 'vala'
brew 'valabind'
brew 'vimpager'
brew 'w3m'
brew 'watch'
brew 'watchman'
brew 'webkit2png'
brew 'webp'
brew 'wget'
brew 'whatmask'
brew 'wrk'
brew 'x264'
brew 'xmlstarlet'
brew 'xvid'
brew 'xz'
brew 'yara'
brew 'yarn'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-completions'

tap 'homebrew/dupes'
brew 'diffutils'
brew 'gpatch'
brew 'grep', args: ['with-default-names']
brew 'gzip'
brew 'less'
brew 'openssh'
brew 'rsync'

tap 'homebrew/fuse'
brew 'sshfs'

tap 'homebrew/php'
brew 'composer'
brew 'php71'
brew 'php71-redis'
brew 'php71-xdebug'

tap 'homebrew/services'

tap 'homebrew/versions'

tap 'neovim/neovim'
brew 'neovim'

tap 'rcmdnk/file'
brew 'brew-file'

# App Store applications
#appstore '409203825 Numbers (4.0.5)'
#appstore '409201541 Pages (6.0.5)'
#appstore '866773894 Quiver (3.0.3)'
#appstore '507257563 Sip (4.5.1)'
#appstore '896450579 Textual (6.0.6)'
#appstore '557168941 Tweetbot (2.4.6)'
#appstore '497799835 Xcode (8.2.1)'
