
# tap repositories and their packages

tap caskroom/cask
cask 1password
cask adium
cask adobe-creative-cloud
cask aerial
cask airflow
cask alcatraz
cask alfred
cask android-studio
cask appcleaner
cask atom
cask beamer
cask bettertouchtool
cask betterzipql
cask bitbar
cask charles
cask cocoapods
cask cyberduck
cask dash
cask diffmerge
cask dropbox
cask electrum
cask exa
cask fiddler
cask firefox
cask gear-player
cask gitup
cask google-chrome
cask hopper-disassembler
cask hosts
cask hyperterm
cask imageoptim
cask jadengeller-helium
cask java
cask jetbrains-toolbox
cask karabiner
cask kitematic
cask launchrocket
cask mono-mdk
cask mou
cask mumble
cask onyx
cask osxfuse
cask paw
cask polymail
cask postman
cask provisionql
cask psequel
cask qlcolorcode
cask qlimagesize
cask qlmarkdown
cask qlprettypatch
cask qlstephen
cask quicklook-csv
cask quicklook-json
cask seil
cask sequel-pro
cask skype
cask slack
cask sourcetree
cask spectacle
cask sqlpro-studio
cask sshfs
cask steam
cask suspicious-package
cask taskpaper
cask textual
cask torbrowser
cask totalfinder
cask tower
cask vagrant-manager
cask vagrant
cask virtualbox
cask visual-studio-code
cask vlc
cask webpquicklook
cask wireshark
cask xquartz
cask yakyak

tap caskroom/fonts
cask font-fira-code
cask font-roboto
cask font-source-code-pro

tap caskroom/versions
cask airmail-beta
cask firefoxdeveloperedition
cask google-chrome-canary
cask iterm2-beta

tap homebrew/bundle

tap homebrew/command-not-found

tap homebrew/completions
brew brew-cask-completion
brew docker-compose-completion
brew docker-machine-completion

tap homebrew/core
brew aircrack-ng
brew android-platform-tools
brew ansible
brew apktool
brew asciiquarium
brew autoconf
brew automake
brew awscli
brew bash-completion
brew bfg
brew binutils
brew boost
brew boxes
brew carthage
brew ccat
brew cloc
brew cmatrix
brew cocoapods
brew coreutils
brew cowsay
brew curl
brew dateutils
brew dex2jar
brew diff-so-fancy
brew dockviz
brew dos2unix
brew fasd
brew ffmpeg
brew findutils --with-default-names
brew fortune
brew freetype
brew fzf
brew gawk
brew gcc
brew gdbm
brew gettext
brew ghq
brew git-extras
brew git-fixup
brew git-ftp
brew git
brew glew
brew gmp
brew gnu-sed --with-default-names
brew gnu-tar --with-default-names
brew gnu-which --with-default-names
brew go
brew gource
brew gradle
brew grc
brew gti
brew heroku
brew highlight
brew hr
brew html2text
brew htop-osx
brew httpie
brew hub
brew icdiff
brew icu4c
brew iftop
brew imagemagick --with-webp
brew iozone
brew ipcalc
brew isl
brew jpeg
brew jq
brew lame
brew lastpass-cli --with-pinentry --with-doc
brew lftp
brew libassuan
brew libevent
brew libewf
brew libffi
brew libgpg-error
brew libmagic
brew libmpc
brew libpng
brew libsass
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libxml2
brew libyaml
brew lua
brew lua51
brew mariadb
brew mas
brew miller
brew mongodb
brew moreutils
brew mpfr
brew mtr
brew multitail
brew mycli
brew netcat
brew ngrep
brew nmap
brew no-more-secrets
brew node
brew oniguruma
brew openssl
brew p7zip
brew pcre
brew phantomjs
brew pixman
brew pkg-config
brew pngcheck
brew postgresql
brew pup
brew pv
brew pwntools
brew python
brew python3
brew radare2
brew readline
brew reattach-to-user-namespace --with-wrap-launchctl
brew redis
brew renameutils
brew ruby
brew sassc
brew screenfetch
brew sdl2
brew sdl2_image
brew sl
brew slackcat
brew slurm
brew socat
brew spark
brew sqlite
brew ssh-copy-id
brew stormssh
brew stow
brew surfraw
brew syncthing-inotify
brew syncthing
brew textql
brew the_silver_searcher
brew tig
brew tmux
brew tree
brew unfs3
brew unixodbc
brew v8
brew watch
brew watchman
brew webkit2png
brew webp
brew wget
brew wrk
brew x264
brew xvid
brew xz
brew yara
brew youtube-dl
brew z
brew zsh

tap homebrew/dupes
brew diffutils
brew gpatch
brew grep --with-default-names
brew gzip
brew less
brew rsync

tap homebrew/php
brew composer
brew drupalconsole
brew drush
brew php71
brew psysh
brew wp-cli

tap homebrew/services

tap homebrew/versions

tap rcmdnk/file
brew brew-file

# Cask applications
cask python

# App Store applications
appstore 409203825 Numbers
appstore 409201541 Pages
appstore 866773894 Quiver
appstore 557168941 Tweetbot
appstore 497799835 Xcode
