#!/usr/bin/env bash

autoload -Uz colors && colors
local color tty=1 is_bold=false
local -a text

while (( $# > 0 )); do
    case "$1" in
        --color)
            if [[ ! $2 =~ ^(black|blue|cyan|default|green|grey|magenta|red|white|yellow)$ ]]; then
                command printf -- "$2: must be a color" >&2
                return 1
            fi
            color="$2"; shift
            ;;
        --bold)
            is_bold=true
            ;;
        --tty)
            if [[ $2 != <-> ]]; then
                command printf -- "$2: must be an interger" >&2
                return 1
            fi
            tty="$2"; shift
            ;;
        *)
            text+=("$1")
            ;;
    esac
    shift
done

if $is_bold; then
    color="$fg_bold[$color]"
else
    color="$fg_no_bold[$color]"
fi

case $tty in
    1)
        command printf -- "${color}${text}${reset_color}"
        ;;
    2)
        command printf -- "${color}${text}${reset_color}" >&2
        ;;
esac