#!/usr/bin/env zsh

emulate -L zsh

local shallow=0 print=0 update=0 vcs=git

while getopts spu opt; do
	case $opt in
		(s)
			shallow=1
		;;
		(p)
			print=1
		;;
		(u)
			update=1
		;;
	esac
done
shift $(( OPTIND - 1 ))

local cloneopts=(--vcs $vcs)
local query=$1

if (( $shallow )) {
  cloneopts+=(--shallow)
}

if (( $update )) {
  cloneopts+=(-u)
}

ghq get $cloneopts "$query"

location="$(ghq list -p $query)"

if (( $print )); then
	ghq list -p $location
else
	cd "$location"
fi
