#!/usr/bin/env zsh

curl -so /dev/null -w "\
   namelookup:  %{time_namelookup}
	  connect:  %{time_connect}
   appconnect:  %{time_appconnect}
  pretransfer:  %{time_pretransfer}
	 redirect:  %{time_redirect}
starttransfer:  %{time_starttransfer}
-------------------------
		total:  %{time_total}\n"  "$@"
