#!/usr/bin/env zsh

# create a data URL from a file
local mimeType=`file -b --mime-type "$1"`

if [[ $mimeType == text/* ]]; then
	mimeType="${mimeType};charset=utf-8"
fi
echo "data:${mimeType};base64,$(base64 -w 0 "$1")"
