#!/usr/bin/env zsh
emulate -L zsh

local clearcache=false readall=false command

while getopts tcr opt; do
    case $opt in
        (c)
            clearcache=true
        ;;
    esac
done
shift $(( OPTIND - 1 ))
command="$@"

if $clearcache; then
    antibody update
    rm -rf "$TMPPREFIX" $ZDOTDIR/.zcompdump{,.zwc}(N)
    ink -c green -- "- Cleared Caches -"
fi

if [[ -n $command ]]; then
    zsh -ic "$command; exit"
    return
fi

exec zsh -i
