#!/usr/bin/env zsh
emulate -L zsh

local clearcache=false readall=false command

while getopts tcr opt; do
    case $opt in
        (c)
            clearcache=true
        ;;
        (r)
            readall=true
        ;;
    esac
done
shift $(( OPTIND - 1 ))
command="$@"

if $clearcache; then
    rm -rf $TMPPREFIX
    rm -f $ZDOTDIR/zcompdump
    ink -c green -- "- Cleared Caches -"
fi

if [[ -n $command ]]; then
    if $readall; then
        command+=" | cat -A"
    fi
    zsh -ic "$command; exit"
    return
fi

exec zsh -i
