#!/usr/bin/env zsh
emulate -L zsh

local clearcache=false restarttmux=false readall=false command autoload_functions

while getopts tcr opt; do
    case $opt in
        (t)
            restarttmux=true
        ;;
        (c)
            clearcache=true
        ;;
        (r)
            readall=true
        ;;
    esac
done
shift $(( OPTIND - 1 ))
command="$@"

if $clearcache; then
    rm -rf $TMPPREFIX
    print -l "Cleared Caches"
    return
fi

if [[ -n $command ]]; then
    if $readall; then
        command+=" | cat -A"
    fi
    zsh -ic "$command; exit"
    return
fi

exec zsh -i
