#!/usr/bin/env zsh

# scan incoming traffic.

local device='en0'
local port=80

case "$#" in
	1) device="$1";;
	2) device="$1"
		port="$2";;
	*) ;;
esac

sudo ngrep -d ${device} -t '^(GET|POST) ' "tcp and port ${port}"
