#!/usr/bin/env zsh

# z is the new j? I guess?

text="$@"
if [[ -z "$text" ]]; then
    # Print with score
    cd "$(fasd -d "$text" | fzf-tmux | awk '{print $2}')"
    return
fi

directory=$(fasd -ld "$text" | head -n1)
if [[ -z $directory ]]; then
    ink -c red -t 2 'No Directory found'
    return 1
fi

cd "$directory"
