#!/usr/bin/env zsh
emulate -L zsh

local clearcache=false readall=false command

while getopts tcr opt; do
    case $opt in
        (c)
            clearcache=true
        ;;
    esac
done
shift $(( OPTIND - 1 ))
command="$@"

if $clearcache; then
    antidote update
    rm -rf "$TMPPREFIX" $ZDOTDIR/.zcompdump $ZDOTDIR/{*,.*}.zwc(-.N)
    ink -c green -- "- Cleared Caches -"
fi

if [[ -n $command ]]; then
    SHLVL=0 zsh -c "$command; exit"
    return
fi

exec zsh
