#!/usr/bin/env zsh

local pip=pip2

if (( $+commands[pip] )) {
	pip=pip
}

(( $+commands[$pip] )) || return 34

ink -l -c green "[python] installing python packages"

$pip install -U \
	pip setuptools \
	virtualenv \
	pygments \
	tamper \
	doge

pip3 install -U \
	pip \
	git-repo
