#!/usr/bin/env zsh

(( $+commands[gem] )) || exit 34

ink -l -c green "[ruby] installing/updating gems"
gem update --system

(( $+commands[bundle])) || gem install bundler
bundle install --system --gemfile="$XDG_CONFIG_HOME"/ruby/Gemfile
