#!/usr/bin/env zsh

(( $+commands[node] )) || exit 34

ink -l -c green -- "[node] Installing npm Packages"
npm install -g \
    npm \
    babel-cli \
    bcat \
    ctrace \
    fkill-cli \
    gulp \
    speed-test \
    spoof \
    yo
