#!/usr/bin/env zsh

# Making some directories
mkdir -p "$XDG_DATA_HOME/node" "$XDG_DATA_HOME/zsh"

# virtualbox
if (( $+commands[VBoxManage] )) {
	ink -c green "[virtualbox] setting default folder for virtualbox"
	VBoxManage setproperty machinefolder "$XDG_DATA_HOME/Virtualbox VMs"
}

# grc
if (( $+commands[grc] )) && [[ $OSTYPE =~ darwin ]] && [[ ! -L /usr/local/etc/grc.conf ]] {
	ink -c green "[colors] Symlinking grc config"
	ln -s $XDG_CONFIG_HOME/grc/grc.conf /usr/local/etc/grc.conf
}

