#!/usr/bin/env zsh

# hushlogin
touch ~/.hushlogin

# vscode
if [[ -f ~/Dropbox/Apps/VSCode && ! -L ~/.vscode/extensions ]] {
    # Symlink vscode to the right directory until https://github.com/Microsoft/vscode/issues/3884 is resolved.
    ink -lc green "[vscode] Linking vscode extension dir"
    mkdir -p ~/.vscode
    ln -sT ~/Dropbox/Apps/VSCode/extensions ~/.vscode/extensions
}

# virtualbox
if (( $+commands[VBoxManage] )) {
    ink -lc green "[virtualbox] setting default folder for virtualbox"
    VBoxManage setproperty machinefolder "$XDG_DATA_HOME/Virtualbox VMs"
}

# dnsmasq
if (( $+commands[dnsmasq] )) && [[ -f $XDG_CONFIG_HOME/dnsmasq/dnsmasq.conf ]] {
    # Need password for dnsmasq
    ink -lc green "[dnsmasq] Setting up dnsmasq config"
    sudo -v

    ln -fs $XDG_CONFIG_HOME/dnsmasq/dnsmasq.conf /usr/local/etc/dnsmasq.conf

    ink -c green "[dnsmasq] Setting up .dev resolver"
    sudo mkdir -p /etc/resolver
    sudo tee /etc/resolver/dev >/dev/null <<-EOF
nameserver 127.0.0.1
EOF
}

# grc
if (( $+commands[grc] )) && [[ $OSTYPE =~ darwin ]] && [[ ! -L /usr/local/etc/grc.conf ]] {
    ink -lc green "[colors] Symlinking grc config"
    symlink-files -yq $XDG_CONFIG_HOME/grc/grc.conf /usr/local/etc/
}
