#!/usr/bin/env zsh

[[ $OSTYPE =~ darwin ]] || exit 34

# @TODO - Having issues with running from ~
cd $XDG_CONFIG_HOME

brewfile() {
	brew-file -F bundle -f "$XDG_CONFIG_HOME/brew/brewfile" "$@"
}

# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.
ink -l -c green -- "[brew] Installing/Upgrading Brews from file"
brewfile -C update

ink -l -c green -- "[brew] Upgrading Casks"
brewfile cask_upgrade -C

ink -l -c green -- "[brew] Cleaning"
brewfile clean -C

ink -l -c green -- "[brew] Cleaning Non Requested"
brewfile clean_non_request -C

gnufiles=($HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin/*)
manfiles=($HOMEBREW_PREFIX/opt/coreutils/libexec/gnuman/man1/*)

ink -l -c green "[brew] Symlinking gnu man files"
# Link Man Files that aren't linked by default
symlink-files -q "$gnufiles" "$HOMEBREW_PREFIX/bin"
symlink-files -q "$manfiles" "$HOMEBREW_PREFIX/share/man/man1"
