#!/usr/bin/env zsh

(( $+commands[nvim] )) || exit 34

dot_path=$(realpath "$(dirname $0)/../")

if [[ ! -f $XDG_DATA_HOME/nvim/site/autoload/plug.vim ]]; then
	ink -c green "[vim] Downloading plug.vim."
	curl -sfLo $XDG_DATA_HOME/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# nvim
ink -c green "[vim] Installing nvim plugins."
nvim +PlugInstall +qall
