#!/usr/bin/env zsh

[[ $OSTYPE =~ darwin ]] || exit 34

local plist_dir="$XDG_CONFIG_HOME"/macos

# User LaunchAgents
for file in $plist_dir/LaunchAgents/*(N.); do
	filename="${file:t}"
	service_name="${filename:r}"
	service_location=~/Library/LaunchAgents/"$filename"

	ink -l -c green -- "[plist] Setting up $service_name"

	# Replace $HOME
	sed "s|\$HOME|$HOME|g" "$file" > "$service_location"
	chmod 644 "$service_location"

	domain_target="gui/$UID"
	service_target="$domain_target/$service_name"
	launchctl bootout "$domain_target" "$service_location"
	# load is deprecated. Can't get bootstrap/enable to actually enable
	launchctl load -w "$service_location"
	# launchctl bootstrap "$domain_target" "$service_location"
	# launchctl kickstart "$service_target"
done
