#!/usr/bin/env zsh

(( $+commands[vagrant])) || exit 34

vagrant plugin install vagrant-auto_network \
			vagrant-cachier \
			vagrant-gatling-rsync \
			vagrant-hostsupdater

sudo tee /etc/sudoers.d/vagrant <<-SUDOERS
# For Vagrant NFS
Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
Cmnd_Alias VAGRANT_NFSD = /sbin/nfsd restart
Cmnd_Alias VAGRANT_EXPORTS_REMOVE= $(which sed) -E -e /*/ d -ibak /etc/exports
# For vagrant-hostsupdater
Cmnd_Alias VAGRANT_HOSTS_ADD = /bin/sh -c echo "*" >> /etc/hosts
Cmnd_Alias VAGRANT_HOSTS_REMOVE = $(which sed) -i -e /*/ d /etc/hosts
%admin ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE, VAGRANT_HOSTS_ADD, VAGRANT_HOSTS_REMOVE
SUDOERS