#!/usr/bin/env zsh

[[ $OSTYPE =~ darwin ]] || exit 34

local plist_dir=~/.dotfiles/etc/plists

# User LaunchAgents
for file in $plist_dir/LaunchAgents/*; do
    filename=${file:t}
    service_location=~/Library/LaunchAgents/$filename

    ink -l -c green -- "[plist] Setting up $filename"

    chown $USER $service_location
    chmod 600 $service_location
    cp $file $service_location
    launchctl unload $service_location 2>/dev/null
    launchctl load $service_location
done

# Root LaunchAgents
for file in $plist_dir/LaunchAgentsRoot/*; do
    filename=${file:t}
    service_location=/Library/LaunchAgents/$filename

    ink -l -c yellow -- "[plist] Setting up $filename"

    sudo cp $file $service_location
    sudo chown root $service_location
    sudo chmod 600 $service_location
    sudo launchctl unload $service_location 2>/dev/null
    sudo launchctl load $service_location
done
