#!/usr/bin/env zsh

autoload -Uz colors

while getopts c:lbt: opt; do
    case $opt in
        (c)
            if [[ ! $OPTARG =~ ^(black|blue|cyan|default|green|grey|magenta|red|white|yellow)$ ]]; then
                print -- "$OPTARG: must be a color" >&2
                return 1
            fi
            inkcolor=$OPTARG
            ;;
        (l)
            is_new_line=true
        ;;
        (b)
            is_bold=true
            ;;
        (t)
            if [[ $OPTARG != <-> ]]; then
                print -- "$OPTARG: must be an interger" >&2
                return 1
            fi
            tty="$OPTARG"
            ;;
    esac
done
shift $(( OPTIND - 1 ))

if [[ $* == '-' ]]; then
    while IFS= read -r line; do
        text+=($line) ;
    done
    shift
fi

text+=($*)

if $is_bold; then
    inkcolor="$fg_bold[$inkcolor]"
else
    inkcolor="$fg_no_bold[$inkcolor]"
fi

$is_new_line && text_after="\n" || text_after=""

text=${inkcolor}${text}${reset_color}${text_after}

case $tty in
    (2)
        print -- $text >&2
        ;;
    (*)
        print -- $text
        ;;
esac
