#!/usr/bin/env zsh
emulate -L zsh

local clearcache=false restarttmux=false readall=false command autoload_functions

while getopts tcr opt; do
    case $opt in
        (t)
            restarttmux=true
        ;;
        (c)
            clearcache=true
        ;;
        (r)
            readall=true
        ;;
    esac
done
shift $(( OPTIND - 1 ))
command="$@"

if $clearcache; then
    rm -f $DOTFILES_CACHE_DIR/{fasd-init.sh,antibody-plugins.sh,zcompdump,zcompdump.zwc}
    print -l "Cleared Caches"
fi

if $restarttmux && [[ -n $TMUX ]] ; then
    # Doesn't work since it kills this session...
    { tmux kill-server  && tmuxx && print -l "Restarted Tmux" }&!
fi

if [[ -n $command ]]; then
    if $readall; then
        command+=" | cat -A"
    fi
    zsh -ic "$command; exit"
else
    print -l "Re-sourced .zshrc"

    # Reload functions that were autoloaded, @TODO: Find a better way to do this
    autoload_functions=( $DOTFILES/**/autoload/* )

    local f
    for f in $autoload_functions:t; do
        unfunction $f
        autoload -Uz $f
    done

    source $HOME/.zshrc
fi
