#!/usr/bin/env zsh
emulate -L zsh

(alias; declare -f) | command which -a --tty-only --read-alias --read-functions --show-dot --show-tilde $@
local inspect="$1"

hr '-'

if [[ $+commands[$command] ]]; then
    local path=${:==$inspect}
    print $path
    stat --printf '%N' =$inspect
fi

hr '-'

