npm install grunt -g
npm install gulp -g
npm install bower -g
npm install newman -g
npm install yo -g
npm install coffee-script -g
npm install bless -g
npm install tldr -g
npm install speed-test -g
npm install spoof -g
