#!/usr/bin/env zsh

# Lets you cd into local sites (doesn't work with vagrant)

local l="$1"
local first=${l:0:1}

if [[ -z $1 ]] || [[ $first != "@" && $first != "%" ]]; then
    builtin cd $*
    return
fi

d="$(drush drupal-directory $1 --local-only 2>/dev/null)"
if [[ $? == 0 ]]; then
    builtin cd "$d";
    return
fi

if drush site-alias $1 >/dev/null 2>&1; then
    echo "Cannot cd to remote site $s" >&2
else
    echo "Cannot cd to $s" >&2
fi
